name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/cache@v3
        id: cache-deno
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}

      - name: Fetch deps
        if: ${{ steps.cache-deno.outputs.cache-hit != 'true' }}
        run: deno cache -r deps.ts

      - name: Test
        run: deno test -A

      - name: DNT
        run: deno run -A script/build_npm.ts